name: Deploy to AWS EC2

on:
    pull_request:
        types:
          - closed
        branches:
          - "main"
        paths:
          - 'backend/**'

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
        - name: Checkout the files
          uses: actions/checkout@v4

        - name: Create environment file
          run: |
              cp .env.example .env

        - name: Deploy to the server
          uses: easingthemes/ssh-deploy@v4
          with:
            SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
            REMOTE_HOST: ${{ secrets.EC2_HOST }}
            REMOTE_USER: ${{ secrets.EC2_USER }}
            TARGET: /home/${{ secrets.EC2_USER }}/JunEmpower
            ARGS: "-rlgoDzvc -i --delete"
            EXCLUDE: "/infra/, /.git/, /backend/app/logs/, /backend/app/examples/, /backend/app/htmlcov/"
            SCRIPT_BEFORE: |
                whoami
                ls -al
            SCRIPT_AFTER: |
                whoami
                ls -al
                chmod +x ./deployment/scripts/rebuild.sh
                cd deployment && ./scripts/rebuild.sh