# Generated by Django 4.2.4 on 2023-10-23 09:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectimage",
            name="image",
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name="project_image"),
        ),
    ]
