version: '3.3'
services:
  db:
    container_name: my_db
    image: postgres:alpine3.18
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=db_platform404
    volumes:
      - ./docker/db:/var/lib/postgresql/data
      - ./extension.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - my-network

  nginx:
    image: nginx:1.23-alpine
    volumes:
      - .:/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 1443:80
    networks:
      - my-network


  app:
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    ports:
      - 8000:5000
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - my-network
    depends_on:
      - db

networks:
  my-network:
    driver: bridge