version: '3.8'
services:
  db:
    container_name: my_db
    image: postgres:alpine3.18
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=db_platform404
    volumes:
      - ./docker/db:/var/lib/postgresql/data
      - ./extension.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - dev

  app:
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    ports:
      - 8000:5000
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - dev
    depends_on:
      - db

networks:
  dev:
    driver: bridge