version: '3.3'
services:
  db:
    container_name: my_db
    image: postgres:alpine3.18
    # restart: always - good for production
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./docker/db:/var/lib/postgresql/data/pgdata
      - ./extension.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    networks:
      - my-network

  nginx:
    image: nginx:1.23-alpine
    # restart: always
    volumes:
      - .:/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 1443:80
    networks:
      - my-network

  app:
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    ports:
      - 8000:5000
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - my-network

networks:
  my-network:
    driver: bridge