version: '3.3'
services:
  db:
    container_name: my_db
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_platform404
    volumes:
      - ./docker/db:/var/lib/mysql
    ports:
      - '3308:3306'
    networks:
      - my-network

  nginx:
    image: nginx:1.23-alpine
    volumes:
      - .:/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 1443:80
    networks:
      - my-network

  app:
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    ports:
      - 8080:5000
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - my-network

networks:
  my-network:
    driver: bridge