[tool.black]
target-version = ['py38']
line-length = 120
include = '\.pyi?$'
force-exclude = '''
(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | venv
  | _build
  | buck-out
  | build
  | dist
  | main/migrations
  | \.csv$
  | \.sql$
  | \.txt$
  | LICENSE
  | docker-compose\.yml
  | pyproject.toml
)
'''

[tool.isort]
multi_line_output = 3
line_length = 120
include_trailing_comma = true
