# Generated by Django 4.2.4 on 2023-08-29 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_customuser_email_alter_project_author_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="tags",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name="ProjectImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="uploads/img/project/")),
                ("is_main", models.BooleanField(default=False)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="main.project",
                    ),
                ),
            ],
        ),
    ]
