# Generated by Django 4.2.4 on 2023-09-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_alter_customuser_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="author_id",
            new_name="author",
        ),
        migrations.RenameField(
            model_name="project",
            old_name="name",
            new_name="title",
        ),
        migrations.RenameField(
            model_name="technology",
            old_name="technology",
            new_name="title",
        ),
        migrations.AddField(
            model_name="specialization",
            name="slug",
            field=models.CharField(default="slug", max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name="technology",
            name="slug",
            field=models.CharField(default="slug", max_length=100, unique=True),
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="specialization_id",
        ),
        migrations.RemoveField(
            model_name="project",
            name="technology",
        ),
        migrations.AddField(
            model_name="customuser",
            name="specialization_id",
            field=models.ManyToManyField(
                blank=True, null=True, to="main.specialization"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="technology",
            field=models.ManyToManyField(blank=True, null=True, to="main.technology"),
        ),
    ]
