# Generated by Django 4.2.4 on 2023-09-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_rename_author_id_project_author_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specialization",
            name="slug",
            field=models.CharField(default="slug", max_length=100),
        ),
    ]
