# Generated by Django 4.2.4 on 2023-09-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_rename_author_id_comment_author_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="in_development",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="project",
            name="is_compiled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="link_deploy",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="link_hub",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="specialization",
            field=models.ManyToManyField(blank=True, to="main.specialization"),
        ),
        migrations.AlterField(
            model_name="project",
            name="technology",
            field=models.ManyToManyField(blank=True, to="main.technology"),
        ),
    ]
