# Generated by Django 4.2.4 on 2023-09-16 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_project_in_development_project_is_compiled_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="like",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="main.project",
            ),
        ),
    ]
