# Generated by Django 4.2.4 on 2023-09-16 17:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_alter_like_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
