# Generated by Django 4.2.4 on 2023-09-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0012_project_created_project_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specialization",
            name="slug",
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="specialization",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="technology",
            name="slug",
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="technology",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
