# Generated by Django 4.2.4 on 2023-10-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_remove_project_in_development_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="about",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="linkedin",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="repo",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="telegram",
            field=models.URLField(blank=True, null=True),
        ),
    ]
