# Generated by Django 4.2.4 on 2023-10-01 16:48

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0018_project_title_gin_idx_project_description_gin_idx"),
    ]

    # operations = [
    #     migrations.AddIndex(
    #         model_name="project",
    #         index=django.contrib.postgres.indexes.GinIndex(
    #             fields=["title"], name="title_gin_idx"
    #         ),
    #     ),
    #     migrations.AddIndex(
    #         model_name="project",
    #         index=django.contrib.postgres.indexes.GinIndex(
    #             fields=["description"], name="description_gin_idx"
    #         ),
    #     ),
    # ]
