# Generated by Django 4.2.4 on 2023-10-10 18:37

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0020_rename_date_comment_created_comment_text_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="title",
            field=models.TextField(max_length=100),
        ),
        migrations.AddIndex(
            model_name="project",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["title"], name="title_gin_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["description"], name="description_gin_idx"
            ),
        ),
    ]
