name: Deploy to AWS EC2

on:
    pull_request:
        types:
          - closed
        branches:
          - "main"
    push:
        branches:
          - "main"

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
        - name: Checkout the files
          uses: actions/checkout@v4

        - name: Deploy to the server
          uses: easingthemes/ssh-deploy@v4
          with:
            SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
            REMOTE_HOST: ${{ secrets.EC2_HOST }}
            REMOTE_USER: ${{ secrets.EC2_USER }}
            TARGET: /home/${{ secrets.EC2_USER }}/JunEmpower/server
            SCRIPT_AFTER: |
                cd /home/${{ secrets.EC2_USER }}/JunEmpower/server
                git pull
                cp .env.example.deploy .env
                sudo docker-compose up --build -d
                docker ps
